project:
  type: website

website:
  title: "Bach"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - intro.qmd
      - equations.qmd
      - modflow.qmd
      - demo.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

bibliography: references.bib
juypter: julia-1.8
